server:
  port: 9527
  
spring:
  application:
    # 集群时对外暴露的统一的服务实例名
    name: microservicecloud-zuul-gateway
    
eureka:
  client:
    service-url:
      # 客户端注册进eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    # 自定义服务名称信息
    instance-id: MicroservicecloudZuulGateway9527
    prefer-ip-address: true
    
# 微服务info内容详细信息    
info: 
  app.name: study-springcloud
  company.name: PickRecalled
  build.artifactId: $project.artifactId$
  build.version: $project.version$