server:
  port: 9527
  
spring:
  application:
    # 集群时对外暴露的统一的服务实例名
    name: microservicecloud-zuul-gateway
    
eureka:
  client:
    service-url:
      # 客户端注册进eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    # 自定义服务名称信息
    instance-id: MicroservicecloudZuulGateway9527
    prefer-ip-address: true
    
zuul: 
  # 统一公共前缀
  prefix: /pickrecalled
  # 原真实服务名忽略
  # ignored-services: microservicecloud-provider-dept
  # 使用*的方式
  ignored-services: "*"
  # 服务名映射
  routes: 
    # 隐藏真实服务名
    mydept.serviceId: microservicecloud-provider-dept
    # 展示服务名
    mydept.path: /provider-dept/**

    
# 微服务info内容详细信息    
info: 
  app.name: study-springcloud
  company.name: PickRecalled
  build.artifactId: $project.artifactId$
  build.version: $project.version$